version: 0.0
os: windows
files:
  - source: /build/
    destination: C:\inetpub\wwwroot\cliente2
    ignore:
      - '*.config'
hooks:
  BeforeInstall:
    - location: \before-iis-install-stop.bat
      timeout: 900
  AfterInstall:
    - location: \after-iis-install-start.bat
      timeout: 180
