version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
  pre_build:
    commands:
      - echo "Restaurando paquetes NuGet..."
      - dotnet restore
  build:
    commands:
      - echo "Compilando la solución..."
      - dotnet build
  post_build:
    commands:
      - echo "Publicando la API..."
      - dotnet publish -c Release -f net5.0 -o /tmp/publish
artifacts:
  files:
    - /tmp/publish/**
